FROM dart:stable AS build

WORKDIR /app

COPY pubspec.* ./

RUN dart pub get

COPY . .

RUN dart compile exe bin/jualbeli_backend.dart -o bin/server


FROM debian:bookworm-slim

WORKDIR /app

COPY --from=build /app/bin/server /app/server
COPY --from=build app/isrgrootx1.pem app/isrgrootx1.pem 

EXPOSE 8080

CMD ["/app/server"]