FROM dart:stable AS build

WORKDIR /app

COPY pubspec.* ./

RUN dart pub get

COPY . .

RUN dart compile exe bin/jualbeli_backend.dart -o bin/server


FROM debian:bookworm-slim

WORKDIR /app

COPY --from=build /runtime/ /
COPY --from=build /app/bin/server /app/server

ENV PORT=8080

EXPOSE 8080

CMD ["/app/server"]